# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AccelerationSet4Way_PB.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AccelerationSet4Way_PB.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1c\x41\x63\x63\x65lerationSet4Way_PB.proto\"M\n\x16\x41\x63\x63\x65lerationSet4Way_PB\x12\x0b\n\x03lon\x18\x01 \x02(\x05\x12\x0b\n\x03lat\x18\x02 \x02(\x05\x12\x0c\n\x04vert\x18\x03 \x02(\x05\x12\x0b\n\x03yaw\x18\x04 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ACCELERATIONSET4WAY_PB = _descriptor.Descriptor(
  name='AccelerationSet4Way_PB',
  full_name='AccelerationSet4Way_PB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lon', full_name='AccelerationSet4Way_PB.lon', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lat', full_name='AccelerationSet4Way_PB.lat', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vert', full_name='AccelerationSet4Way_PB.vert', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='AccelerationSet4Way_PB.yaw', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['AccelerationSet4Way_PB'] = _ACCELERATIONSET4WAY_PB

AccelerationSet4Way_PB = _reflection.GeneratedProtocolMessageType('AccelerationSet4Way_PB', (_message.Message,), dict(
  DESCRIPTOR = _ACCELERATIONSET4WAY_PB,
  __module__ = 'AccelerationSet4Way_PB_pb2'
  # @@protoc_insertion_point(class_scope:AccelerationSet4Way_PB)
  ))
_sym_db.RegisterMessage(AccelerationSet4Way_PB)


# @@protoc_insertion_point(module_scope)
