# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExteriorLights_PB.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import String_PB_pb2 as String__PB__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ExteriorLights_PB.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x17\x45xteriorLights_PB.proto\x1a\x0fString_PB.proto\"\xa4\x03\n\x11\x45xteriorLights_PB\x12#\n\x0f\x65teriorlights_t\x18\x01 \x02(\x0b\x32\n.String_PB\"\xe9\x02\n\x0e\x45xteriorLights\x12&\n\"ExteriorLights_lowBeamHeadlightsOn\x10\x00\x12\'\n#ExteriorLights_highBeamHeadlightsOn\x10\x01\x12#\n\x1f\x45xteriorLights_leftTurnSignalOn\x10\x02\x12$\n ExteriorLights_rightTurnSignalOn\x10\x03\x12!\n\x1d\x45xteriorLights_hazardSignalOn\x10\x04\x12*\n&ExteriorLights_automaticLightControlOn\x10\x05\x12)\n%ExteriorLights_daytimeRunningLightsOn\x10\x06\x12\x1d\n\x19\x45xteriorLights_fogLightOn\x10\x07\x12\"\n\x1e\x45xteriorLights_parkingLightsOn\x10\x08')
  ,
  dependencies=[String__PB__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_EXTERIORLIGHTS_PB_EXTERIORLIGHTS = _descriptor.EnumDescriptor(
  name='ExteriorLights',
  full_name='ExteriorLights_PB.ExteriorLights',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ExteriorLights_lowBeamHeadlightsOn', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ExteriorLights_highBeamHeadlightsOn', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ExteriorLights_leftTurnSignalOn', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ExteriorLights_rightTurnSignalOn', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ExteriorLights_hazardSignalOn', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ExteriorLights_automaticLightControlOn', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ExteriorLights_daytimeRunningLightsOn', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ExteriorLights_fogLightOn', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ExteriorLights_parkingLightsOn', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=104,
  serialized_end=465,
)
_sym_db.RegisterEnumDescriptor(_EXTERIORLIGHTS_PB_EXTERIORLIGHTS)


_EXTERIORLIGHTS_PB = _descriptor.Descriptor(
  name='ExteriorLights_PB',
  full_name='ExteriorLights_PB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eteriorlights_t', full_name='ExteriorLights_PB.eteriorlights_t', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EXTERIORLIGHTS_PB_EXTERIORLIGHTS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=465,
)

_EXTERIORLIGHTS_PB.fields_by_name['eteriorlights_t'].message_type = String__PB__pb2._STRING_PB
_EXTERIORLIGHTS_PB_EXTERIORLIGHTS.containing_type = _EXTERIORLIGHTS_PB
DESCRIPTOR.message_types_by_name['ExteriorLights_PB'] = _EXTERIORLIGHTS_PB

ExteriorLights_PB = _reflection.GeneratedProtocolMessageType('ExteriorLights_PB', (_message.Message,), dict(
  DESCRIPTOR = _EXTERIORLIGHTS_PB,
  __module__ = 'ExteriorLights_PB_pb2'
  # @@protoc_insertion_point(class_scope:ExteriorLights_PB)
  ))
_sym_db.RegisterMessage(ExteriorLights_PB)


# @@protoc_insertion_point(module_scope)
