# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control_command.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
import chassis_pb2 as chassis__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='control_command.proto',
  package='chassis',
  syntax='proto2',
  serialized_pb=_b('\n\x15\x63ontrol_command.proto\x12\x07\x63hassis\x1a\x0cheader.proto\x1a\rchassis.proto\"\xa4\x05\n\x0e\x43ontrolCommand\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.common.Header\x12\x33\n\npilot_mode\x18\x02 \x01(\x0e\x32\x12.chassis.PilotMode:\x0bMODE_MANUAL\x12\x13\n\x08steering\x18\x03 \x01(\x02:\x01\x30\x12\x10\n\x05speed\x18\x04 \x01(\x02:\x01\x30\x12\x10\n\x05\x61\x63\x63\x65l\x18\x05 \x01(\x02:\x01\x30\x12\x13\n\x08throttle\x18\x06 \x01(\x02:\x01\x30\x12\x10\n\x05\x62rake\x18\x07 \x01(\x02:\x01\x30\x12.\n\x04gear\x18\x08 \x01(\x0e\x32\x15.chassis.GearPosition:\tGEAR_NONE\x12/\n\x05light\x18\t \x01(\x0e\x32\x14.chassis.LightSwitch:\nLIGHT_NONE\x12\x13\n\x04horn\x18\n \x01(\x08:\x05\x66\x61lse\x12\x17\n\x08highbeam\x18\x0b \x01(\x08:\x05\x66\x61lse\x12\x16\n\x07lowbeam\x18\x0c \x01(\x08:\x05\x66\x61lse\x12\x17\n\x08\x66oglight\x18\r \x01(\x08:\x05\x66\x61lse\x12\x1e\n\x0f\x63learance_lamps\x18\x0e \x01(\x08:\x05\x66\x61lse\x12\x19\n\nwarn_light\x18\x0f \x01(\x08:\x05\x66\x61lse\x12\x1c\n\rparking_brake\x18\x10 \x01(\x08:\x05\x66\x61lse\x12\x15\n\x06\x66wiper\x18\x11 \x01(\x08:\x05\x66\x61lse\x12\x1a\n\x0b\x62rake_light\x18\x12 \x01(\x08:\x05\x66\x61lse\x12\x11\n\tdrive_off\x18\x14 \x01(\x08\x12\x13\n\x0b\x64\x65\x63_to_stop\x18\x15 \x01(\x08\x12\x1f\n\x10location_missing\x18\x16 \x01(\x08:\x05\x66\x61lse\x12!\n\x12trajectory_missing\x18\x17 \x01(\x08:\x05\x66\x61lse\x12%\n\x16\x63hassis_status_missing\x18\x18 \x01(\x08:\x05\x66\x61lse')
  ,
  dependencies=[header__pb2.DESCRIPTOR,chassis__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CONTROLCOMMAND = _descriptor.Descriptor(
  name='ControlCommand',
  full_name='chassis.ControlCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='chassis.ControlCommand.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pilot_mode', full_name='chassis.ControlCommand.pilot_mode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='steering', full_name='chassis.ControlCommand.steering', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='chassis.ControlCommand.speed', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accel', full_name='chassis.ControlCommand.accel', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='throttle', full_name='chassis.ControlCommand.throttle', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='brake', full_name='chassis.ControlCommand.brake', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gear', full_name='chassis.ControlCommand.gear', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='light', full_name='chassis.ControlCommand.light', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='horn', full_name='chassis.ControlCommand.horn', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='highbeam', full_name='chassis.ControlCommand.highbeam', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lowbeam', full_name='chassis.ControlCommand.lowbeam', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='foglight', full_name='chassis.ControlCommand.foglight', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clearance_lamps', full_name='chassis.ControlCommand.clearance_lamps', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='warn_light', full_name='chassis.ControlCommand.warn_light', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parking_brake', full_name='chassis.ControlCommand.parking_brake', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fwiper', full_name='chassis.ControlCommand.fwiper', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='brake_light', full_name='chassis.ControlCommand.brake_light', index=17,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='drive_off', full_name='chassis.ControlCommand.drive_off', index=18,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dec_to_stop', full_name='chassis.ControlCommand.dec_to_stop', index=19,
      number=21, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location_missing', full_name='chassis.ControlCommand.location_missing', index=20,
      number=22, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trajectory_missing', full_name='chassis.ControlCommand.trajectory_missing', index=21,
      number=23, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chassis_status_missing', full_name='chassis.ControlCommand.chassis_status_missing', index=22,
      number=24, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=740,
)

_CONTROLCOMMAND.fields_by_name['header'].message_type = header__pb2._HEADER
_CONTROLCOMMAND.fields_by_name['pilot_mode'].enum_type = chassis__pb2._PILOTMODE
_CONTROLCOMMAND.fields_by_name['gear'].enum_type = chassis__pb2._GEARPOSITION
_CONTROLCOMMAND.fields_by_name['light'].enum_type = chassis__pb2._LIGHTSWITCH
DESCRIPTOR.message_types_by_name['ControlCommand'] = _CONTROLCOMMAND

ControlCommand = _reflection.GeneratedProtocolMessageType('ControlCommand', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLCOMMAND,
  __module__ = 'control_command_pb2'
  # @@protoc_insertion_point(class_scope:chassis.ControlCommand)
  ))
_sym_db.RegisterMessage(ControlCommand)


# @@protoc_insertion_point(module_scope)
