info:
  - code: IMAP_ENTRY_AUTOPILOT
    msg: 控制进入自动驾驶成功


error:
  - code: EMAP_EXIT_AUTOPILOT_FOR_PLANNING
    msg: 因planning掉帧强退自动驾驶
    result: 
      - RESULT_AUTOPILOT_INFERIOR
    action: 
      - ACTION_CONTACT_TECH_SUPPORT

  - code: EMAP_EXIT_AUTOPILOT_FOR_LOCATION
    msg: 因location掉帧强退自动驾驶
    result: 
      - RESULT_AUTOPILOT_INFERIOR
    action: 
      - ACTION_CONTACT_TECH_SUPPORT

  - code: EMAP_EXIT_AUTOPILOT_FOR_CHASSIS
    msg: 因底盘消息掉帧强退自动驾驶
    result: 
      - RESULT_AUTOPILOT_INFERIOR
    action: 
      - ACTION_CONTACT_TECH_SUPPORT

  - code: EMAP_EXIT_AUTOPILOT_FOR_DISTANCE
    msg: 因planning起点距离当前过远强退自动驾驶
    result: 
      - RESULT_AUTOPILOT_INFERIOR
    action: 
      - ACTION_CONTACT_TECH_SUPPORT

  - code: EMAP_EXIT_AUTOPILOT_FOR_BRAKE
    msg: 制动踏板干预而强退自动驾驶
    result: 
      - RESULT_AUTOPILOT_INFERIOR
    action: 
      - ACTION_CONTACT_TECH_SUPPORT

  - code: EMAP_EXIT_AUTOPILOT_FOR_ACCEL
    msg: 加速踏板干预而强退自动驾驶
    result: 
      - RESULT_AUTOPILOT_INFERIOR
    action: 
      - ACTION_CONTACT_TECH_SUPPORT

  - code: EMAP_EXIT_AUTOPILOT_FOR_STEER
    msg: 方向盘干预而强退自动驾驶
    result: 
      - RESULT_AUTOPILOT_INFERIOR
    action: 
      - ACTION_CONTACT_TECH_SUPPORT

  - code: EMAP_EXIT_AUTOPILOT_FOR_GEAR_SWITCH
    msg: 档位切换干预而强退自动驾驶
    result: 
      - RESULT_AUTOPILOT_INFERIOR
    action: 
      - ACTION_CONTACT_TECH_SUPPORT

  - code: EMAP_EXIT_AUTOPILOT_FOR_CHASSIS_NO_RESPONSE
    msg: 底盘不响应请求而强退自动驾驶
    result: 
      - RESULT_AUTOPILOT_INFERIOR
    action: 
      - ACTION_CONTACT_TECH_SUPPORT

  - code: EMAP_EXIT_AUTOPILOT_FOR_CHASSIS_UNKNOWN
    msg: 底盘退出原因未知而强退自动驾驶
    result: 
      - RESULT_AUTOPILOT_INFERIOR
    action: 
      - ACTION_CONTACT_TECH_SUPPORT

  - code: EVHC_GEAR
    msg: 档位不是D或N档
    result: 
      - RESULT_AUTOPILOT_DISABLE
      - RESULT_REMOTEPILOT_DISABLE
    action: 
      - ACTION_HANDLE_VEHICLE_TURN_GEAR
      - ACTION_TRY_AGAIN_LATER
    
  - code: EMAP_ENTRY_AUTOPILOT_FOR_CANADAPTER_TIMEOUT
    msg: can_adapter消息超时未进入自驾
    result: 
      - RESULT_AUTOPILOT_DISABLE
    action: 
      - ACTION_CONTACT_TECH_SUPPORT

  - code: EMAP_ENTRY_AUTOPILOT_FOR_PLANNING_TIMEOUT
    msg: PLANNING消息超时未进自驾
    result: 
      - RESULT_AUTOPILOT_DISABLE
    action: 
      - ACTION_CONTACT_TECH_SUPPORT

  - code: EMAP_ENTRY_AUTOPILOT_FOR_LOCATION_TIMEOUT
    msg: 定位消息超时未进自驾
    result: 
      - RESULT_AUTOPILOT_DISABLE
    action: 
      - ACTION_CONTACT_TECH_SUPPORT

  - code: EMAP_ENTRY_AUTOPILOT_FOR_BRAKE
    msg: 制动踏板干预未进自驾
    result: 
      - RESULT_AUTOPILOT_DISABLE
    action: 
      - ACTION_TRY_AGAIN_LATER

  - code: EMAP_ENTRY_AUTOPILOT_FOR_ACCEL
    msg: 加速踏板干预未进自驾
    result: 
      - RESULT_AUTOPILOT_DISABLE
    action: 
      - ACTION_TRY_AGAIN_LATER

  - code: EMAP_ENTRY_AUTOPILOT_FOR_STEER
    msg: 方向盘干预未进自驾
    result: 
      - RESULT_AUTOPILOT_DISABLE
    action: 
      - ACTION_TRY_AGAIN_LATER

  - code: EMAP_ENTRY_AUTOPILOT_FOR_GEAR_SWITCH
    msg: 档位切换干预未进自驾
    result: 
      - RESULT_AUTOPILOT_DISABLE
    action: 
      - ACTION_TRY_AGAIN_LATER

  - code: EMAP_ENTRY_AUTOPILOT_FOR_OTHER_CTL
    msg: 其他干预未进自驾，请检查仪表盘和开关项(如双闪，制动灯灯等 可在msg中补充原因信息)
    result: 
      - RESULT_AUTOPILOT_DISABLE
    action: 
      - ACTION_TRY_AGAIN_LATER