info:
  - code: ISYS_STARTING
    msg: 系统启动中

  - code: ISYS_RUNNING
    msg: 所有Xavier启动完成

  - code: ISYS_EXITING
    msg: 系统退出中

  - code: ISYS_AUTOPILOT_READY
    msg: 自动驾驶状态就绪

  - code: ISYS_AUTOPILOT_STARTING
    msg: 自动驾驶启动中

  - code: ISYS_AUTOPILOT_RUNING
    msg: 自动驾驶运行中

  - code: ISYS_TOPIC_FREQ_NORMAL
    msg: topic频率正常或者恢复正常

  - code: ISYS_CAN_NORMAL
    msg: 底盘状态正常或恢复正常

  - code: ISYS_REOMTEPILOT_STARTING
    msg: 平行驾驶启动中

  - code: ISYS_REOMTEPILOT_RUNING
    msg: 平行驾驶运行中

  - code: ISYS_SYSTEM_IN_IDLE
    msg: 系统进入空闲状态

  - code: ISYS_SYSTEM_OUT_IDLE
    msg: 系统退出空闲状态

  - code: ILCT_RTK_STATUS_NORMAL
    msg: rtk状态正常或恢复正常

  - code: ILCT_RTK_OR_SLAM_CHANGE
    msg: 定位输出源发生RTK和SLAM变换

  - code: ISYS_INIT_TRAJECTORY_START
    msg: 轨迹管理_轨迹开始下载

  - code: ISYS_INIT_TRAJECTORY_SUCCESS
    msg: 轨迹管理_轨迹下载成功

  - code: ISYS_INIT_TRAJECTORY_FAILURE
    msg: 轨迹管理_轨迹下载失败，本地无对应轨迹

  - code: ISYS_INIT_TRAJECTORY_WARNING
    msg: 轨迹管理_轨迹下载失败，本地有对应轨迹，认为成功

  - code: ISYS_INIT_TRAJECTORY_TIMEOUT
    msg: 轨迹管理_轨迹下载超时

error:
  - code: ESYS_AUTOPILOT_FAILED
    msg: 在尝试启动自动驾驶，但是超过指定时间后底盘未进入，会发送此事件
    result: 
      - RESULT_AUTOPILOT_INFERIOR
      - RESULT_AUTOPILOT_DISABLE
    action: 
      - ACTION_TRY_AGAIN_LATER
      - ACTION_CONTACT_TECH_SUPPORT

  - code: ESYS_IN_EXIT
    msg: 系统处于退出中，拒绝进入自动驾驶/远程驾驶
    result: 
      - RESULT_AUTOPILOT_DISABLE

  - code: ESYS_NOT_ALLOW_AUTOPILOT_FOR_REMOTE
    msg: 系统处于远程驾驶中，拒绝进入自动驾驶
    result: 
      - RESULT_AUTOPILOT_DISABLE

  - code: ESYS_NOT_ALLOW_REBOOT
    msg: 重启拒绝
    action: 
      - ACTION_TRY_AGAIN_LATER

  - code: ESYS_TOPIC_FREQ_DROPED
    msg: 存在topic严重掉频
    result: 
      - RESULT_AUTOPILOT_INFERIOR

  - code: ESYS_AUTOPILOT_TAKEN_OVER_BY_REMOTE
    msg: 自动驾驶被远程驾驶接管
    result: 
      - RESULT_AUTOPILOT_DISABLE

  - code: ESYS_ROUTING_REQ_TIMEOUT
    msg: 自动驾驶开始前，routing请求无响应
    result: 
      - RESULT_AUTOPILOT_DISABLE
    action: 
      - ACTION_TRY_AGAIN_LATER

  - code: ESYS_PLANNING_CHANGE_FAILIED
    msg: planning版本切换启动失败
    result: 
      - RESULT_AUTOPILOT_DISABLE
    action: 
      - ACTION_CONTACT_TECH_SUPPORT

  - code: ESYS_CHECK_TRAJECTORY_FAILURE
    msg: 轨迹文件检查超时或检查结果无可用轨迹
    result: 
      - RESULT_AUTOPILOT_DISABLE
    action: 
      - ACTION_TRY_AGAIN_LATER

  - code: ESYS_FAULT
    msg: master启动10分钟，仍有agent未连接
    result: 
      - RESULT_AUTOPILOT_DISABLE
    action: 
      - ACTION_REBOOT_VEHICLE

  - code: ELCT_RTK_STATUS_FAULT
    msg: RTK状态错误
    result: 
      - RESULT_AUTOPILOT_DISABLE
    action: 
      - ACTION_CONTACT_TECH_SUPPORT

  - code: ELCT_RTK_STATUS_UNKNOWN
    msg: RTK状态不确定
    result: 
      - RESULT_SHOW_WARNING

  - code: ESYS_CAN_MSG_LOST
    msg: master接收底盘消息超时
    result: 
      - RESULT_AUTOPILOT_DISABLE
      - RESULT_AUTOPILOT_INFERIOR
    action: 
      - ACTION_CONTACT_TECH_SUPPORT

  - code: ESYS_REBOOT_WARNING
    msg: 命令重启不完全提示
    action: 
      - ACTION_CONTACT_TECH_SUPPORT