cp -p guardian_config.20.json  ./DFHYD08117/guardian/guardian_config.json
cp -p guardian_config.20.json  ./DFHYD02130/guardian/guardian_config.json
cp -p guardian_config.20.json  ./DFHYD01501/guardian/guardian_config.json
cp -p guardian_config.20.json  ./DFHYD05063/guardian/guardian_config.json
cp -p guardian_config.20.json  ./DFHYD00437/guardian/guardian_config.json
cp -p guardian_config.20.json  ./DFHYD00419/guardian/guardian_config.json
cp -p guardian_config.20.json  ./DFHYD08546/guardian/guardian_config.json
cp -p guardian_config.20.json  ./DFHYD04257/guardian/guardian_config.json
cp -p guardian_config.20.json  ./DFHYD08427/guardian/guardian_config.json
cp -p guardian_config.20.json  ./DFHYD02313/guardian/guardian_config.json
cp -p guardian_config.20.json  ./DFHYD00479/guardian/guardian_config.json
cp -p guardian_config.20.json  ./DFHYD01201/guardian/guardian_config.json
cp -p guardian_config.20.json  ./DFHYD03372/guardian/guardian_config.json
cp -p guardian_config.20.json  ./DFHYD00843/guardian/guardian_config.json
cp -p guardian_config.20.json  ./DFHYD08047/guardian/guardian_config.json
cp -p guardian_config.20.json  ./DFHYD01082/guardian/guardian_config.json
cp -p guardian_config.20.json  ./DFHYD00343/guardian/guardian_config.json
cp -p guardian_config.20.json  ./DFHYD00142/guardian/guardian_config.json
cp -p guardian_config.20.json  ./DFHYD09240/guardian/guardian_config.json
cp -p guardian_config.20.json  ./DFHYD02182/guardian/guardian_config.json

cp -p guardian_config.30.json  ./DFHYD00908/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD09929/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD04161/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD04842/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD03988/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD07000/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD01793/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD00340/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD07425/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD03041/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD00442/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD06619/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD07042/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD01092/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD00799/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD00141/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD01362/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD01625/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD03556/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD07407/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD00507/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD09035/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD06440/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD02020/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD05276/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD00412/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD07430/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD01717/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD08822/guardian/guardian_config.json
cp -p guardian_config.30.json  ./DFHYD09941/guardian/guardian_config.json

cp -p guardian_config.20.json ./JLBJ1861378/guardian/guardian_config.json
cp -p guardian_config.20.json ./JLBJ1861380/guardian/guardian_config.json
cp -p guardian_config.20.json ./JLBJ1861382/guardian/guardian_config.json
cp -p guardian_config.20.json ./JLHY1861379/guardian/guardian_config.json
cp -p guardian_config.20.json ./JLHY1861381/guardian/guardian_config.json
cp -p guardian_config.20.json ./JLHY1861383/guardian/guardian_config.json
cp -p guardian_config.20.json ./JLHY1861384/guardian/guardian_config.json
cp -p guardian_config.20.json ./JLHY1861385/guardian/guardian_config.json
cp -p guardian_config.20.json ./JLHY1861386/guardian/guardian_config.json
cp -p guardian_config.20.json ./JLHY1861387/guardian/guardian_config.json


cp -p guardian_config.20.json ./CCBJA6NW86/guardian/guardian_config.json
cp -p guardian_config.20.json ./CCBJA7HL79/guardian/guardian_config.json
cp -p guardian_config.20.json ./CCBJA8PA20/guardian/guardian_config.json
cp -p guardian_config.20.json ./CCBJQ3TS20/guardian/guardian_config.json


cp -p guardian_config.20.json ./BYDBJA22872/guardian/guardian_config.json
cp -p guardian_config.20.json ./BYDSUED89087/guardian/guardian_config.json
cp -p guardian_config.20.json ./BYDTJADK2721/guardian/guardian_config.json
