# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system_cmd.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='system_cmd.proto',
  package='system_master',
  syntax='proto2',
  serialized_pb=_b('\n\x10system_cmd.proto\x12\rsystem_master\x1a\x0cheader.proto\"\x86\x01\n\tSystemCmd\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.common.Header\x12#\n\x03src\x18\x02 \x02(\x0e\x32\x16.system_master.cmd_src\x12&\n\x06\x61\x63tion\x18\x03 \x02(\x0e\x32\x16.system_master.cmd_act\x12\x0c\n\x04\x64\x65sc\x18\x04 \x01(\t*5\n\x07\x63md_src\x12\n\n\x06Unknow\x10\x00\x12\r\n\tAutoPolit\x10\x01\x12\x0f\n\x0bRemotePilot\x10\x02*i\n\x07\x63md_act\x12\x0c\n\x08Noaction\x10\x00\x12\r\n\tSysReboot\x10\x01\x12\x0e\n\nStartPilot\x10\x02\x12\r\n\tStopPilot\x10\x03\x12\x11\n\rBeginShowMode\x10\x04\x12\x0f\n\x0b\x45ndShowMode\x10\x05')
  ,
  dependencies=[header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_CMD_SRC = _descriptor.EnumDescriptor(
  name='cmd_src',
  full_name='system_master.cmd_src',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unknow', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AutoPolit', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RemotePilot', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=186,
  serialized_end=239,
)
_sym_db.RegisterEnumDescriptor(_CMD_SRC)

cmd_src = enum_type_wrapper.EnumTypeWrapper(_CMD_SRC)
_CMD_ACT = _descriptor.EnumDescriptor(
  name='cmd_act',
  full_name='system_master.cmd_act',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Noaction', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SysReboot', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='StartPilot', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='StopPilot', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BeginShowMode', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EndShowMode', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=241,
  serialized_end=346,
)
_sym_db.RegisterEnumDescriptor(_CMD_ACT)

cmd_act = enum_type_wrapper.EnumTypeWrapper(_CMD_ACT)
Unknow = 0
AutoPolit = 1
RemotePilot = 2
Noaction = 0
SysReboot = 1
StartPilot = 2
StopPilot = 3
BeginShowMode = 4
EndShowMode = 5



_SYSTEMCMD = _descriptor.Descriptor(
  name='SystemCmd',
  full_name='system_master.SystemCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='system_master.SystemCmd.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='src', full_name='system_master.SystemCmd.src', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action', full_name='system_master.SystemCmd.action', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='desc', full_name='system_master.SystemCmd.desc', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=184,
)

_SYSTEMCMD.fields_by_name['header'].message_type = header__pb2._HEADER
_SYSTEMCMD.fields_by_name['src'].enum_type = _CMD_SRC
_SYSTEMCMD.fields_by_name['action'].enum_type = _CMD_ACT
DESCRIPTOR.message_types_by_name['SystemCmd'] = _SYSTEMCMD
DESCRIPTOR.enum_types_by_name['cmd_src'] = _CMD_SRC
DESCRIPTOR.enum_types_by_name['cmd_act'] = _CMD_ACT

SystemCmd = _reflection.GeneratedProtocolMessageType('SystemCmd', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEMCMD,
  __module__ = 'system_cmd_pb2'
  # @@protoc_insertion_point(class_scope:system_master.SystemCmd)
  ))
_sym_db.RegisterMessage(SystemCmd)


# @@protoc_insertion_point(module_scope)
