# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hadmap_traffic_light.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
import geometry_pb2 as geometry__pb2
import hadmap_pb2 as hadmap__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hadmap_traffic_light.proto',
  package='hadmap',
  syntax='proto2',
  serialized_pb=_b('\n\x1ahadmap_traffic_light.proto\x12\x06hadmap\x1a\x0cheader.proto\x1a\x0egeometry.proto\x1a\x0chadmap.proto\"K\n\x16TrafficLightReliedInfo\x12\x0e\n\x06roadId\x18\x01 \x01(\x04\x12\x11\n\tsectionId\x18\x02 \x01(\x04\x12\x0e\n\x06laneId\x18\x03 \x01(\x04\"\x8d\x02\n\x0cTrafficLight\x12\x0c\n\x04pkid\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tattribute\x18\x03 \x01(\t\x12\x33\n\x0brelied_info\x18\x04 \x03(\x0b\x32\x1e.hadmap.TrafficLightReliedInfo\x12\x1d\n\x04geom\x18\x05 \x03(\x0b\x32\x0f.geometry.Point\x12\x0b\n\x03row\x18\x06 \x01(\x04\x12\x0b\n\x03\x63ol\x18\x07 \x01(\x04\x12\x0e\n\x06height\x18\x08 \x01(\x01\x12&\n\x04type\x18\t \x03(\x0e\x32\x18.hadmap.TrafficLightType\x12(\n\x05shape\x18\n \x01(\x0e\x32\x19.hadmap.TrafficLightShape\"<\n\rTrafficLights\x12+\n\rtraffic_light\x18\x01 \x03(\x0b\x32\x14.hadmap.TrafficLight\"a\n\x10TrafficLightsMsg\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.common.Header\x12-\n\x0etraffic_lights\x18\x02 \x01(\x0b\x32\x15.hadmap.TrafficLights*\xc5\x02\n\x10TrafficLightType\x12\x1e\n\x1aTRAFFIC_LIGHT_TYPE_Regular\x10\x01\x12\x1c\n\x18TRAFFIC_LIGHT_TYPE_Arrow\x10\x02\x12&\n\"TRAFFIC_LIGHT_TYPE_Countdown_Board\x10\x03\x12\x1c\n\x18TRAFFIC_LIGHT_TYPE_UTurn\x10\x04\x12 \n\x1cTRAFFIC_LIGHT_TYPE_Turn_Left\x10\x05\x12\x1f\n\x1bTRAFFIC_LIGHT_TYPE_Straight\x10\x06\x12!\n\x1dTRAFFIC_LIGHT_TYPE_Turn_Right\x10\x07\x12$\n TRAFFIC_LIGHT_TYPE_Non_Motorized\x10\x08\x12!\n\x1dTRAFFIC_LIGHT_TYPE_Lights_Off\x10\t*u\n\x11TrafficLightShape\x12!\n\x1dTRAFFIC_LIGHT_SHAPE_Rectangle\x10\x01\x12\x1e\n\x1aTRAFFIC_LIGHT_SHAPE_Circle\x10\x02\x12\x1d\n\x19TRAFFIC_LIGHT_SHAPE_Other\x10\x03')
  ,
  dependencies=[header__pb2.DESCRIPTOR,geometry__pb2.DESCRIPTOR,hadmap__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_TRAFFICLIGHTTYPE = _descriptor.EnumDescriptor(
  name='TrafficLightType',
  full_name='hadmap.TrafficLightType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRAFFIC_LIGHT_TYPE_Regular', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRAFFIC_LIGHT_TYPE_Arrow', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRAFFIC_LIGHT_TYPE_Countdown_Board', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRAFFIC_LIGHT_TYPE_UTurn', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRAFFIC_LIGHT_TYPE_Turn_Left', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRAFFIC_LIGHT_TYPE_Straight', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRAFFIC_LIGHT_TYPE_Turn_Right', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRAFFIC_LIGHT_TYPE_Non_Motorized', index=7, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRAFFIC_LIGHT_TYPE_Lights_Off', index=8, number=9,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=593,
  serialized_end=918,
)
_sym_db.RegisterEnumDescriptor(_TRAFFICLIGHTTYPE)

TrafficLightType = enum_type_wrapper.EnumTypeWrapper(_TRAFFICLIGHTTYPE)
_TRAFFICLIGHTSHAPE = _descriptor.EnumDescriptor(
  name='TrafficLightShape',
  full_name='hadmap.TrafficLightShape',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRAFFIC_LIGHT_SHAPE_Rectangle', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRAFFIC_LIGHT_SHAPE_Circle', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRAFFIC_LIGHT_SHAPE_Other', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=920,
  serialized_end=1037,
)
_sym_db.RegisterEnumDescriptor(_TRAFFICLIGHTSHAPE)

TrafficLightShape = enum_type_wrapper.EnumTypeWrapper(_TRAFFICLIGHTSHAPE)
TRAFFIC_LIGHT_TYPE_Regular = 1
TRAFFIC_LIGHT_TYPE_Arrow = 2
TRAFFIC_LIGHT_TYPE_Countdown_Board = 3
TRAFFIC_LIGHT_TYPE_UTurn = 4
TRAFFIC_LIGHT_TYPE_Turn_Left = 5
TRAFFIC_LIGHT_TYPE_Straight = 6
TRAFFIC_LIGHT_TYPE_Turn_Right = 7
TRAFFIC_LIGHT_TYPE_Non_Motorized = 8
TRAFFIC_LIGHT_TYPE_Lights_Off = 9
TRAFFIC_LIGHT_SHAPE_Rectangle = 1
TRAFFIC_LIGHT_SHAPE_Circle = 2
TRAFFIC_LIGHT_SHAPE_Other = 3



_TRAFFICLIGHTRELIEDINFO = _descriptor.Descriptor(
  name='TrafficLightReliedInfo',
  full_name='hadmap.TrafficLightReliedInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roadId', full_name='hadmap.TrafficLightReliedInfo.roadId', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sectionId', full_name='hadmap.TrafficLightReliedInfo.sectionId', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='laneId', full_name='hadmap.TrafficLightReliedInfo.laneId', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=157,
)


_TRAFFICLIGHT = _descriptor.Descriptor(
  name='TrafficLight',
  full_name='hadmap.TrafficLight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pkid', full_name='hadmap.TrafficLight.pkid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='hadmap.TrafficLight.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='hadmap.TrafficLight.attribute', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='relied_info', full_name='hadmap.TrafficLight.relied_info', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='geom', full_name='hadmap.TrafficLight.geom', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='row', full_name='hadmap.TrafficLight.row', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='col', full_name='hadmap.TrafficLight.col', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='hadmap.TrafficLight.height', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='hadmap.TrafficLight.type', index=8,
      number=9, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shape', full_name='hadmap.TrafficLight.shape', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=429,
)


_TRAFFICLIGHTS = _descriptor.Descriptor(
  name='TrafficLights',
  full_name='hadmap.TrafficLights',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='traffic_light', full_name='hadmap.TrafficLights.traffic_light', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=491,
)


_TRAFFICLIGHTSMSG = _descriptor.Descriptor(
  name='TrafficLightsMsg',
  full_name='hadmap.TrafficLightsMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='hadmap.TrafficLightsMsg.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='traffic_lights', full_name='hadmap.TrafficLightsMsg.traffic_lights', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=590,
)

_TRAFFICLIGHT.fields_by_name['relied_info'].message_type = _TRAFFICLIGHTRELIEDINFO
_TRAFFICLIGHT.fields_by_name['geom'].message_type = geometry__pb2._POINT
_TRAFFICLIGHT.fields_by_name['type'].enum_type = _TRAFFICLIGHTTYPE
_TRAFFICLIGHT.fields_by_name['shape'].enum_type = _TRAFFICLIGHTSHAPE
_TRAFFICLIGHTS.fields_by_name['traffic_light'].message_type = _TRAFFICLIGHT
_TRAFFICLIGHTSMSG.fields_by_name['header'].message_type = header__pb2._HEADER
_TRAFFICLIGHTSMSG.fields_by_name['traffic_lights'].message_type = _TRAFFICLIGHTS
DESCRIPTOR.message_types_by_name['TrafficLightReliedInfo'] = _TRAFFICLIGHTRELIEDINFO
DESCRIPTOR.message_types_by_name['TrafficLight'] = _TRAFFICLIGHT
DESCRIPTOR.message_types_by_name['TrafficLights'] = _TRAFFICLIGHTS
DESCRIPTOR.message_types_by_name['TrafficLightsMsg'] = _TRAFFICLIGHTSMSG
DESCRIPTOR.enum_types_by_name['TrafficLightType'] = _TRAFFICLIGHTTYPE
DESCRIPTOR.enum_types_by_name['TrafficLightShape'] = _TRAFFICLIGHTSHAPE

TrafficLightReliedInfo = _reflection.GeneratedProtocolMessageType('TrafficLightReliedInfo', (_message.Message,), dict(
  DESCRIPTOR = _TRAFFICLIGHTRELIEDINFO,
  __module__ = 'hadmap_traffic_light_pb2'
  # @@protoc_insertion_point(class_scope:hadmap.TrafficLightReliedInfo)
  ))
_sym_db.RegisterMessage(TrafficLightReliedInfo)

TrafficLight = _reflection.GeneratedProtocolMessageType('TrafficLight', (_message.Message,), dict(
  DESCRIPTOR = _TRAFFICLIGHT,
  __module__ = 'hadmap_traffic_light_pb2'
  # @@protoc_insertion_point(class_scope:hadmap.TrafficLight)
  ))
_sym_db.RegisterMessage(TrafficLight)

TrafficLights = _reflection.GeneratedProtocolMessageType('TrafficLights', (_message.Message,), dict(
  DESCRIPTOR = _TRAFFICLIGHTS,
  __module__ = 'hadmap_traffic_light_pb2'
  # @@protoc_insertion_point(class_scope:hadmap.TrafficLights)
  ))
_sym_db.RegisterMessage(TrafficLights)

TrafficLightsMsg = _reflection.GeneratedProtocolMessageType('TrafficLightsMsg', (_message.Message,), dict(
  DESCRIPTOR = _TRAFFICLIGHTSMSG,
  __module__ = 'hadmap_traffic_light_pb2'
  # @@protoc_insertion_point(class_scope:hadmap.TrafficLightsMsg)
  ))
_sym_db.RegisterMessage(TrafficLightsMsg)


# @@protoc_insertion_point(module_scope)
