# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VehicleClassification_PB.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='VehicleClassification_PB.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1eVehicleClassification_PB.proto\"D\n\x18VehicleClassification_PB\x12\x16\n\x0e\x63lassification\x18\x01 \x02(\x05\x12\x10\n\x08\x66uelType\x18\x02 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VEHICLECLASSIFICATION_PB = _descriptor.Descriptor(
  name='VehicleClassification_PB',
  full_name='VehicleClassification_PB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='classification', full_name='VehicleClassification_PB.classification', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fuelType', full_name='VehicleClassification_PB.fuelType', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['VehicleClassification_PB'] = _VEHICLECLASSIFICATION_PB

VehicleClassification_PB = _reflection.GeneratedProtocolMessageType('VehicleClassification_PB', (_message.Message,), dict(
  DESCRIPTOR = _VEHICLECLASSIFICATION_PB,
  __module__ = 'VehicleClassification_PB_pb2'
  # @@protoc_insertion_point(class_scope:VehicleClassification_PB)
  ))
_sym_db.RegisterMessage(VehicleClassification_PB)


# @@protoc_insertion_point(module_scope)
