# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import mogo_report_msg_pb2 as mogo__report__msg__pb2
import carinfo_pb2 as carinfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='monitor_msg.proto',
  package='monitor_msg',
  syntax='proto2',
  serialized_pb=_b('\n\x11monitor_msg.proto\x12\x0bmonitor_msg\x1a\x15mogo_report_msg.proto\x1a\rcarinfo.proto\"_\n\nMonitorMsg\x12!\n\x07\x63\x61rinfo\x18\x01 \x02(\x0b\x32\x10.carinfo.CarInfo\x12.\n\treportmsg\x18\x02 \x02(\x0b\x32\x1b.mogo_msg.MogoReportMessage')
  ,
  dependencies=[mogo__report__msg__pb2.DESCRIPTOR,carinfo__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MONITORMSG = _descriptor.Descriptor(
  name='MonitorMsg',
  full_name='monitor_msg.MonitorMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='carinfo', full_name='monitor_msg.MonitorMsg.carinfo', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reportmsg', full_name='monitor_msg.MonitorMsg.reportmsg', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=167,
)

_MONITORMSG.fields_by_name['carinfo'].message_type = carinfo__pb2._CARINFO
_MONITORMSG.fields_by_name['reportmsg'].message_type = mogo__report__msg__pb2._MOGOREPORTMESSAGE
DESCRIPTOR.message_types_by_name['MonitorMsg'] = _MONITORMSG

MonitorMsg = _reflection.GeneratedProtocolMessageType('MonitorMsg', (_message.Message,), dict(
  DESCRIPTOR = _MONITORMSG,
  __module__ = 'monitor_msg_pb2'
  # @@protoc_insertion_point(class_scope:monitor_msg.MonitorMsg)
  ))
_sym_db.RegisterMessage(MonitorMsg)


# @@protoc_insertion_point(module_scope)
